address_list/address_list/apps/supplier/urls.py
from django.conf.urls import patterns, url

from supplier.views import SupplierList, SupplierCreate, \
    SupplierUpdate, SupplierDelete, SupplierCreateAddress, \
    SupplierSearch

urlpatterns = patterns(
    '',
    url(r'^list/$', SupplierList.as_view(), name='list'),
    url(r'^create/$', SupplierCreate.as_view(), name='create'),
    url(r'^create_address/$', SupplierCreateAddress.as_view(), name='create_address'),
    url(r'^update/(?P<pk>\d+)/$', SupplierUpdate.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', SupplierDelete.as_view(), name='delete'),
    url(r'^search/$', SupplierSearch.as_view(), name='search'),
)

address_list/address_list/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^$', 'core.views.homepage', name='homepage'),
    url(r'^supplier/', include('supplier.urls', namespace='supplier')),
    url(r'^admin/', include(admin.site.urls)),
)

address_list/address_list/apps/core/models.py
from django.db import models

# Create your models here.

address_list/address_list/apps/supplier/models.py
from django.db import models


class Suppliers(models.Model):
    supplier_name = models.CharField(max_length=150, blank=True)
    addresses = models.ManyToManyField('Addresses', blank=True,
                                       verbose_name=u'Suppliers addresses')


class Addresses(models.Model):
    address_line_1 = models.CharField(verbose_name=u'Address line 1',
                                      max_length=255, default='',
                                      null=True, blank=True)
    address_line_2 = models.CharField(verbose_name=u'Address line 2',
                                      max_length=255, default='',
                                      null=True, blank=True)
    phone = models.CharField(u'Phone',
                             max_length=255, default='',
                             null=True, blank=True)
    town = models.CharField(u'Town',
                            max_length=255, default='',
                            null=True, blank=True)
    post_code = models.PositiveIntegerField(null=True)
    fax = models.CharField(u'Fax',
                           max_length=255, default='',
                           null=True, blank=True)
    email = models.EmailField(unique=True)

address_list/address_list/apps/supplier/forms.py
from django import forms
from supplier.models import Suppliers


class SupplierForm(forms.ModelForm):

    class Meta:
        model = Suppliers
        fields = '__all__'

address_list/address_list/apps/core/views.py
from django.shortcuts import render


def homepage(request):
    return render(request, "index.html")

address_list/address_list/apps/supplier/views.py
from django.views.generic import ListView, UpdateView, CreateView, DeleteView

from django.core.urlresolvers import reverse_lazy

from supplier.models import Suppliers, Addresses
from supplier.forms import SupplierForm


class SupplierMixin(object):

    def get_queryset(self):
        return Suppliers.objects.all()


class SupplierList(SupplierMixin, ListView):
    template_name = 'supplier/list.html'


class SupplierCreate(SupplierMixin, CreateView):
    form_class = SupplierForm
    success_url = reverse_lazy('supplier:list')
    template_name = 'supplier/create.html'


class SupplierUpdate(SupplierMixin, UpdateView):
    model = Suppliers
    success_url = reverse_lazy('supplier:list')
    template_name = 'supplier/update.html'


class SupplierDelete(SupplierMixin, DeleteView):
    model = Suppliers
    success_url = reverse_lazy('supplier:list')


class SupplierSearch(ListView):
    template_name = 'supplier/filtered_result.html'

    def get_queryset(self):
        queryset = Suppliers.objects.all()
        return queryset.filter(
            supplier_name__icontains=self.request.GET['query'])


class AddressMixin(object):

    def get_queryset(self):
        return Addresses.objects.all()


class SupplierCreateAddress(AddressMixin, CreateView):
    model = Addresses
    success_url = reverse_lazy('supplier:create')
    template_name = 'supplier/create_addresses.html'

address_list/address_list/templates/base.html
{% load bootstrap3 %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en" class="no-js">
<head>
    {% block head %}

        <meta charset="UTF-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="format-detection" content="telephone=no"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">

        {% block extra_meta %}{% endblock %}

        <title>{% block title %}Suppliers List{% endblock %}</title>

        {% block for_css %}
            <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"/>
        {% endblock %}

        <script src="{% static 'js/jquery-1.10.1.min.js' %}"></script>
        <script src="{% static 'js/jquery-ui.js' %}"></script>
        {% block extra_css %}{% endblock %}

    {% endblock %}
</head>
<body>
    <div class="container">

        {% block header %}
        {% endblock %}

        <div class="content">
            {% block content %} {% endblock %}
        </div>

        <div class="footer-wrapper">
            {% block footer %}            
            {% endblock %}
        </div>
    </div>

    {% block modal_windows %}{% endblock %}

</body>
{% block for_js %}
    <script src="{% static 'js/libs/bootstrap.min.js' %}"></script>
{% endblock %}
{% block extra_js %}{% endblock %}

<!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
</html>

address_list/address_list/templates/index.html
{% extends 'base.html' %}

{% block content %}
<a href='{% url "supplier:list" %}'>Go to Supplier list</a>
{% endblock content%}

address_list/address_list/templates/supplier/create.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
<form action="{% url 'supplier:create' %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">
            {% bootstrap_icon "star" %} Submit
        </button>
    {% endbuttons %}
</form>
<a href='{% url "supplier:create_address" %}'> Add address </a>
{% endblock content %}

address_list/address_list/templates/supplier/create_addresses.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
<form action="{% url 'supplier:create_address' %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">
            {% bootstrap_icon "star" %} Submit
        </button>
    {% endbuttons %}
</form>
{% endblock content %}

address_list/address_list/templates/supplier/filtered_result.html
{% for object in object_list %}
{% if object.addresses.all %}
   {% for address in object.addresses.all %}
	   <tr>
		    <td><a href="{% url 'supplier:update' object.id %}">{{ object.supplier_name }}</a></td>
		    <td>{{ address }}</td>
		    <td>address line 2</td>
		    <td>town</td>
		    <td>post code</td>
		    <td>telephone</td>
		    <td>fax</td>
		    <td>email</td>
		    <td><a href="{% url 'supplier:delete' object.id %}">delete</a></td>
	   </tr>
   {% endfor %}
{% else %}
		<tr>
		    <td><a href="{% url 'supplier:update' object.id %}">{{ object.supplier_name }}</a></td>
		    <td>empty</td>
		    <td>address line 2</td>
		    <td>town</td>
		    <td>post code</td>
		    <td>telephone</td>
		    <td>fax</td>
		    <td>email</td>
			<td><a href="{% url 'supplier:delete' object.id %}">delete</a></td>				    
	   </tr>
{% endif %}
{% endfor %}

address_list/address_list/templates/supplier/list.html
{% extends 'base.html' %}

{% block content %}
<ul>
    <li><a href="{% url 'supplier:create' %}"><span></span>Создать</a></li>
</ul>
<input type="text" placeholder="Type supplier name and press enter" style="width:300px" class='supplier_filter'/>
<table class="table table-hover">
   <caption>Suppliers list</caption>
   <thead>
	    <th>Supplier name</th>
	    <th>address line 1</th>
	    <th>address line 2</th>
	    <th>town</th>
	    <th>post code</th>
	    <th>telephone</th>
	    <th>fax</th>
	    <th>email</th>
		<th>DELETE</th>
   </thead>
   <tbody id="filtered-result">
	   {% for object in object_list %}
	   {% if object.addresses.all %}
		   {% for address in object.addresses.all %}
			   <tr>
				    <td><a href="{% url 'supplier:update' object.id %}">{{ object.supplier_name }}</a></td>
				    <td>{{ address.address_line_1 }}</td>
				    <td>{{ address.address_line_2 }}</td>
				    <td>{{ address.town }}</td>
				    <td>{{ address.post_code }}</td>
				    <td>{{ address.phone }}</td>
				    <td>{{ address.fax }}</td>
				    <td>{{ address.email }}</td>
				    <td><a href="{% url 'supplier:delete' object.id %}">delete</a></td>
			   </tr>
		   {% endfor %}
	   {% else %}
	   		    <tr>
				    <td><a href="{% url 'supplier:update' object.id %}">{{ object.supplier_name }}</a></td>
				    <td>empty</td>
				    <td>address line 2</td>
				    <td>town</td>
				    <td>post code</td>
				    <td>telephone</td>
				    <td>fax</td>
				    <td>email</td>
					<td><a href="{% url 'supplier:delete' object.id %}">delete</a></td>				    
			   </tr>
	   {% endif %}
	   {% endfor %}
   </tbody>

</table>
{% endblock content %}
{% block extra_js %}
<script type="text/javascript">
	var onFilterSubmit = function (event) {
		query = $('.supplier_filter').val()
		$.get("{% url 'supplier:search' %}", {query: query}, function(data){
		  $('#filtered-result').html(data);
		});
	};
	$(document).on('change', '.supplier_filter', onFilterSubmit);
</script>
{% endblock extra_js %}

address_list/address_list/templates/supplier/suppliers_confirm_delete.html
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

address_list/address_list/templates/supplier/update.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
<form action="{% url 'supplier:update' object.pk %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">
            {% bootstrap_icon "star" %} Submit
        </button>
    {% endbuttons %}
</form>
<a href='{% url "supplier:create_address" %}'> Add address </a>
{% endblock content %}